# Site settings
title: Bryant Arturo Dorado Puga
description: Fullstack Developer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bryant A. Dorado Puga
user_description: I like to work and share my thoughts in such a way that my work and discipline is reflected in my performance. I enjoy to collaborate as a team, but at the same time I'm autonomous and very enthusiastic, so I don't depend on somebody to tell what to do, I'm a "doer" and problem solver.
user_title: Fullstack Developer
email: innovasoftconsultores@gmail.com
# twitter_username: lorem_ipsum
github_username:  bryant_a_dorado_puga
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
